### ISSUE TITLE
Typo in notebook?

### ISSUE THREAD

**Issue by abylouw** [masakhane-io/masakhane#64]
Hi,

Thanks for this repository. I tried to run it but I am getting an issue at:

https://github.com/masakhane-io/masakhane/blob/4388d4e484c82bc199c3e3e10c1ea7fdb428bc95/starter_notebook.ipynb#L304

I don't know what 'fr_test_sents' is, is this maybe a typo?

**Comment by ruohoruotsi** [comment]
I think this is an error that was introduced with this commit:https://github.com/masakhane-io/masakhane/commit/ce10b1aabbd2d04f6bf2924d441f85e272d9bf79#diff-dcf4d137651c3c758c827e175f8522c5  for this PR: https://github.com/masakhane-io/masakhane/pull/57 @jaderabbit @juliakreutzer 

I would say go to an earlier version of the repo before this commit and checkout that. Cheers.

**Comment by juliakreutzer** [comment]
Yes! Thanks for spotting it. Please replace with "en_test_sents". This is an artifact from building a new test set for French. I'll fix it.
